[package]
name = "DarkDiscordFix"
version = "0.1.1"
edition = "2021"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"


[package.metadata.windows]
manifest_path = "manifest.xml"